// Noms d'équipes : football-data renvoie l'anglais ("Czechia", "South Korea"…).
// On affiche le français, MAIS on garde l'anglais en base (scoring + matching
// avec le classement). frTeam() ne sert donc qu'à l'AFFICHAGE.

const FR: Record<string, string> = {
  // Europe
  England: "Angleterre",
  Scotland: "Écosse",
  Wales: "Pays de Galles",
  "Northern Ireland": "Irlande du Nord",
  Ireland: "Irlande",
  "Republic of Ireland": "Irlande",
  France: "France",
  Spain: "Espagne",
  Germany: "Allemagne",
  Italy: "Italie",
  Netherlands: "Pays-Bas",
  Belgium: "Belgique",
  Portugal: "Portugal",
  Croatia: "Croatie",
  Switzerland: "Suisse",
  Austria: "Autriche",
  Denmark: "Danemark",
  Sweden: "Suède",
  Norway: "Norvège",
  Poland: "Pologne",
  Ukraine: "Ukraine",
  Serbia: "Serbie",
  "Bosnia-Herzegovina": "Bosnie-Herzégovine",
  Czechia: "Tchéquie",
  "Czech Republic": "Tchéquie",
  Turkey: "Turquie",
  Türkiye: "Turquie",
  Greece: "Grèce",
  Hungary: "Hongrie",
  Romania: "Roumanie",
  Slovakia: "Slovaquie",
  Slovenia: "Slovénie",
  Iceland: "Islande",
  Finland: "Finlande",
  Russia: "Russie",
  Albania: "Albanie",
  "North Macedonia": "Macédoine du Nord",
  Georgia: "Géorgie",
  Montenegro: "Monténégro",
  Kosovo: "Kosovo",
  Luxembourg: "Luxembourg",

  // Amérique du Sud
  Brazil: "Brésil",
  Argentina: "Argentine",
  Uruguay: "Uruguay",
  Colombia: "Colombie",
  Chile: "Chili",
  Peru: "Pérou",
  Ecuador: "Équateur",
  Paraguay: "Paraguay",
  Bolivia: "Bolivie",
  Venezuela: "Venezuela",

  // CONCACAF
  Mexico: "Mexique",
  "United States": "États-Unis",
  USA: "États-Unis",
  Canada: "Canada",
  "Costa Rica": "Costa Rica",
  Panama: "Panama",
  Honduras: "Honduras",
  Jamaica: "Jamaïque",
  "El Salvador": "Salvador",
  Guatemala: "Guatemala",
  "Trinidad and Tobago": "Trinité-et-Tobago",
  Curacao: "Curaçao",
  Curaçao: "Curaçao",
  Haiti: "Haïti",
  Suriname: "Suriname",

  // Asie / Océanie
  Japan: "Japon",
  "South Korea": "Corée du Sud",
  "Korea Republic": "Corée du Sud",
  "North Korea": "Corée du Nord",
  Iran: "Iran",
  "IR Iran": "Iran",
  "Saudi Arabia": "Arabie saoudite",
  Australia: "Australie",
  Qatar: "Qatar",
  Iraq: "Irak",
  "United Arab Emirates": "Émirats arabes unis",
  Uzbekistan: "Ouzbékistan",
  China: "Chine",
  "China PR": "Chine",
  Jordan: "Jordanie",
  Oman: "Oman",
  Bahrain: "Bahreïn",
  Kuwait: "Koweït",
  India: "Inde",
  Indonesia: "Indonésie",
  Thailand: "Thaïlande",
  Vietnam: "Viêt Nam",
  "New Zealand": "Nouvelle-Zélande",

  // Afrique
  Morocco: "Maroc",
  Senegal: "Sénégal",
  Tunisia: "Tunisie",
  Algeria: "Algérie",
  Egypt: "Égypte",
  Nigeria: "Nigeria",
  Ghana: "Ghana",
  Cameroon: "Cameroun",
  "Ivory Coast": "Côte d'Ivoire",
  "Côte d'Ivoire": "Côte d'Ivoire",
  Mali: "Mali",
  "Burkina Faso": "Burkina Faso",
  "South Africa": "Afrique du Sud",
  "DR Congo": "RD Congo",
  "Congo DR": "RD Congo",
  "Cape Verde": "Cap-Vert",
  "Cabo Verde": "Cap-Vert",
  Gabon: "Gabon",
  Guinea: "Guinée",
  Angola: "Angola",
  Zambia: "Zambie",
  "Equatorial Guinea": "Guinée équatoriale",
};

export function frTeam(name: string | null | undefined): string {
  if (!name) return "";
  return FR[name] ?? name;
}
